### ISSUE TITLE
Typo in Template_PhaleronPatho-Datasets.tsv

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/Phaleron-Pathologies#4]
There is a typo in above mentioned file here: https://github.com/RDFBones/Phaleron-Pathologies/blob/robot/Template_PhaleronPatho-Datasets.tsv#L20
`('has part' max 1 pphaleron-patho:ActivityOfOrbitalPorosityLesion)` should be `('has part' max 1 phaleron-patho:ActivityOfOrbitalPorosityLesion)`
One excess "p"

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/6e1d228a5196d7f25e8410ec150b850009d615b8.
